name: Grid Test Site
favicon: null
layout_spectrum: 0.4394
typography_spectrum: 0.68159
title: Grid Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050505'
    - '#e4e9ed'
    - '#aea086'
    - '#78684e'
    - '#2e3563'
  brandStrength: 0.5781238898634911
  lightness: 0.5
  saturation: 0.7434868158306926
  rhythmicContrast: 0.5
purpose: []
