name: Grid Test Site
favicon: null
layout_spectrum: 1
typography_spectrum: 0.68159
title: Grid Test Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9f7b61'
    - '#10100e'
    - '#b9b9c5'
    - '#baf210'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
